In [ ]:
!pip install numpy

In [12]:
import numpy as np
x=(4,5,6)
for j in x:
    print(j/2)

2.0
2.5
3.0


In [106]:
import numpy as np
x= np.array([2,4,6,8,10])
print(x)
x/3
x*3

[ 2  4  6  8 10]


array([ 6, 12, 18, 24, 30])

In [39]:
np.random.randint(9,28,7)

array([10, 16, 20, 18, 20, 24, 14], dtype=int32)

In [48]:
array=np.random.randint(6,12,(4,3))
array

array([[10,  8,  7],
       [11, 10, 11],
       [ 6, 10, 11],
       [10, 11,  9]], dtype=int32)

In [50]:
np.random.randint(90)

38

In [53]:
np.random.randint(24,34,2)

array([32, 27], dtype=int32)

In [102]:
data= np.random.randint(10,25,(4,4))
data

array([[23, 18, 10, 22],
       [11, 17, 17, 14],
       [24, 23, 12, 24],
       [23, 12, 11, 20]], dtype=int32)

In [103]:
data[1:4 , 1:3]

array([[17, 17],
       [23, 12],
       [12, 11]], dtype=int32)

In [143]:
data[0:3,2:4]

array([[20, 18],
       [13, 22],
       [12, 23]], dtype=int32)

In [138]:
data.max()

np.int32(24)

In [139]:
data.min()

np.int32(11)

In [145]:
data.sum()

np.int64(269)

In [146]:
data.mean()

np.float64(16.8125)

In [74]:
#1D array
x=np.array([4,2])
print(x)

[4 2]


In [82]:
#2D array
x=np.array(([5,6,7],[10,8,9]))
print(x)

[[ 5  6  7]
 [10  8  9]]


In [131]:
#3d array
x= np.array([[1,2,3],[4,5,6]]),  ([[7,8,9],[6,8,9]])
print(x)
print(type(x))

(array([[1, 2, 3],
       [4, 5, 6]]), [[7, 8, 9], [6, 8, 9]])
<class 'tuple'>


In [108]:
np.full((2,3),2)

array([[2, 2, 2],
       [2, 2, 2]])

In [129]:
x=np.array([[[1,2,3],[4,5,6]], [[7,8,9],[7,5,9]]])
print(x)
print(type(x))
x.ndim

[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [7 5 9]]]
<class 'numpy.ndarray'>


3

In [199]:
np.arange(0,100,7)

array([ 0,  7, 14, 21, 28, 35, 42, 49, 56, 63, 70, 77, 84, 91, 98])

In [134]:
np.linspace(5,20,4)

array([ 5., 10., 15., 20.])

In [ ]:
np.eye(9)   #refer to identical matrix

In [137]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [148]:
data=(5,7,9)
sum(data)

21

In [150]:
x=np.array([[3,4,5],[2,3,5]])
print(x)
print(x.shape)

[[3 4 5]
 [2 3 5]]
(2, 3)


In [183]:
x=np.array([[3,4,5,],[2,3,5,],[7,8,9,]])
print("original array:\n",x)
x.shape=(1,9)
print(x)
print("changed array:\n",x)

original array:
 [[3 4 5]
 [2 3 5]
 [7 8 9]]
[[3 4 5 2 3 5 7 8 9]]
changed array:
 [[3 4 5 2 3 5 7 8 9]]


In [206]:
x=np.arange(27)

x.shape=[3,3,3]
print(x)
x.ndim




[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


3

In [5]:
import numpy as np
x= np.array ([[1,2,3],[4,5,6],[7,8,9]])
print(x.shape)
print(x.size)
print(x.ndim)
print(x.dtype)

(3, 3)
9
2
int64


In [15]:
x=np.random.randint(2,34,(5,4))
print(x)

[[18 32 33 19]
 [31  2 31 23]
 [33 16 18 21]
 [24 28 31 21]
 [10  9 32 17]]


In [17]:
x.ravel()

array([18, 32, 33, 19, 31,  2, 31, 23, 33, 16, 18, 21, 24, 28, 31, 21, 10,
        9, 32, 17], dtype=int32)

In [20]:
x.reshape(4,5)

array([[18, 32, 33, 19, 31],
       [ 2, 31, 23, 33, 16],
       [18, 21, 24, 28, 31],
       [21, 10,  9, 32, 17]], dtype=int32)

In [110]:
x1=np.array([[2,3],[4,5]])
print(x1)

[[2 3]
 [4 5]]


In [108]:
x2=np.array([[4,5],[5,6]])
print(x2)

[[4 5]
 [5 6]]


In [111]:
np.vstack([x1,x2])

array([[2, 3],
       [4, 5],
       [4, 5],
       [5, 6]])

In [112]:
np.hstack([x1,x2])

array([[2, 3, 4, 5],
       [4, 5, 5, 6]])

In [ ]:
np.concatenate([x1,x2],axis=0)

In [35]:
np.concatenate([x1,x2],axis=1)

array([[2, 3, 4, 5],
       [4, 5, 5, 6]])

In [41]:
x=np.arange(23,dtype='float')
print(x)
print(x.dtype)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20. 21. 22.]
float64


In [4]:
import numpy as np
x=np.array([1,6])
y=np.array([2,4])
sub=x-y
print(sub)

[-1  2]


In [5]:
np.subtract(x,y)

array([-1,  2])

In [16]:
#broadcasting
x=np.array([[1,2],[4,5],[6,7]])
y=np.array([[5,6]])
addition=x+y
print("broadcasting:\n",addition)

broadcasting:
 [[ 6  8]
 [ 9 11]
 [11 13]]


In [18]:
array1=np.array([[1,2],[4,5],[6,7]])
array2=np.array([[5,6],[4,5],[6,7]])
array=array1-array2
print("subtaction:\n",array)

subtaction:
 [[-4 -4]
 [ 0  0]
 [ 0  0]]


In [21]:

array1=np.array([[1,2],[4,5],[6,7]])
array2=np.array([[5,6],[4,5],[6,7]])
array=array1*array2
print("mutiplication:\n",array)

mutiplication:
 [[ 5 12]
 [16 25]
 [36 49]]


In [19]:
import numpy as np
x=np.array([[1,2,],
             [4,5,]]),  
y=np.array([[7,8,8],
            [7,9,8]])
np.dot(x,y)


array([[[21, 26, 24],
        [63, 77, 72]]])

In [32]:
x=np.arange(10,dtype='float')
print(x)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [47]:
original_array =np.array([10,20,30])
values_to_append=np.array([40,50,60,70,80,90,100])
new_array=np.append( original_array, values_to_append)
print("original array:\n",original_array)
print("values to append:\n",new_array)

original array:
 [10 20 30]
values to append:
 [ 10  20  30  40  50  60  70  80  90 100]


In [100]:
x=np.arange(2,11).reshape(3,3)
print(x)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [113]:
x=np.arange(10,100,10).reshape(3,3)
print(x)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [99]:
first_row=x[0:1]
print("first row of the array:")
print(first_row)

first row of the array:
[[10 20 30]]


In [115]:
last_element=x[2,2]
print("last element of the array:")
print(last_element)

last element of the array:
90
